services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: case
        working_dir: /var/www/html
        tty: true
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - case

    #Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8001:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
        depends_on:
            - web
            - mysql
        networks:
            - case

    #MySQL Service
    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        platform: linux/x86_64
        tty: true
        volumes:
            - mysql-data:/var/lib/mysql
            - mysql-log:/var/log/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - case

#Docker Networks
networks:
    case:
        driver: bridge

volumes:
    mysql-log:
        driver: local
    mysql-data:
        driver: local
